# Curated static reference list of major refineries used for the weather-risk overlay.
# Capacities are approximate public-domain figures (EIA / company disclosures, thousand bpd),
# meant for risk-overlay ranking, not precise capacity accounting.
# "county" (US only) is used to cross-reference the ODIN power-outage feed (data_sources.py) —
# also approximate/best-effort (looked up by refinery city, not surveyed), and note ODIN reports
# Louisiana's parishes under the same "county" field, bare name with no "Parish" suffix.

US_GULF_MIDWEST = [
    {"name": "Motiva Port Arthur", "company": "Motiva (Saudi Aramco)", "state": "TX", "county": "Jefferson", "region": "Gulf Coast",
     "lat": 29.915, "lon": -93.93, "capacity_kbd": 631},
    {"name": "ExxonMobil Beaumont", "company": "ExxonMobil", "state": "TX", "county": "Jefferson", "region": "Gulf Coast",
     "lat": 30.08, "lon": -94.10, "capacity_kbd": 631},
    {"name": "Marathon Galveston Bay (Texas City)", "company": "Marathon", "state": "TX", "county": "Galveston", "region": "Gulf Coast",
     "lat": 29.38, "lon": -94.92, "capacity_kbd": 593},
    {"name": "Marathon Garyville", "company": "Marathon", "state": "LA", "county": "St. John the Baptist", "region": "Gulf Coast",
     "lat": 30.06, "lon": -90.60, "capacity_kbd": 596},
    {"name": "ExxonMobil Baytown", "company": "ExxonMobil", "state": "TX", "county": "Harris", "region": "Gulf Coast",
     "lat": 29.75, "lon": -94.97, "capacity_kbd": 561},
    {"name": "Citgo Lake Charles", "company": "Citgo", "state": "LA", "county": "Calcasieu", "region": "Gulf Coast",
     "lat": 30.20, "lon": -93.30, "capacity_kbd": 425},
    {"name": "Valero Port Arthur", "company": "Valero", "state": "TX", "county": "Jefferson", "region": "Gulf Coast",
     "lat": 29.90, "lon": -93.95, "capacity_kbd": 395},
    {"name": "Valero Corpus Christi", "company": "Valero", "state": "TX", "county": "Nueces", "region": "Gulf Coast",
     "lat": 27.80, "lon": -97.40, "capacity_kbd": 370},
    {"name": "Phillips 66 Sweeny", "company": "Phillips 66", "state": "TX", "county": "Brazoria", "region": "Gulf Coast",
     "lat": 29.07, "lon": -95.68, "capacity_kbd": 247},
    {"name": "Phillips 66 Lake Charles", "company": "Phillips 66", "state": "LA", "county": "Calcasieu", "region": "Gulf Coast",
     "lat": 30.17, "lon": -93.20, "capacity_kbd": 256},
    {"name": "PBF Chalmette", "company": "PBF Energy", "state": "LA", "county": "St. Bernard", "region": "Gulf Coast",
     "lat": 29.95, "lon": -89.96, "capacity_kbd": 190},
    {"name": "Valero Houston", "company": "Valero", "state": "TX", "county": "Harris", "region": "Gulf Coast",
     "lat": 29.73, "lon": -95.23, "capacity_kbd": 205},
    {"name": "BP Whiting", "company": "BP", "state": "IN", "county": "Lake", "region": "Midwest (PADD2)",
     "lat": 41.68, "lon": -87.49, "capacity_kbd": 440},
    {"name": "Phillips 66 Wood River", "company": "Phillips 66", "state": "IL", "county": "Madison", "region": "Midwest (PADD2)",
     "lat": 38.86, "lon": -90.10, "capacity_kbd": 314},
    {"name": "Marathon Catlettsburg", "company": "Marathon", "state": "KY", "county": "Boyd", "region": "Midwest (PADD2)",
     "lat": 38.40, "lon": -82.60, "capacity_kbd": 273},
    {"name": "Marathon Robinson", "company": "Marathon", "state": "IL", "county": "Crawford", "region": "Midwest (PADD2)",
     "lat": 39.00, "lon": -87.70, "capacity_kbd": 253},
    {"name": "HF Sinclair Tulsa", "company": "HF Sinclair", "state": "OK", "county": "Tulsa", "region": "Midwest (PADD2)",
     "lat": 36.10, "lon": -95.90, "capacity_kbd": 125},
    {"name": "CVR Coffeyville", "company": "CVR Energy", "state": "KS", "county": "Montgomery", "region": "Midwest (PADD2)",
     "lat": 37.04, "lon": -95.60, "capacity_kbd": 136},
    {"name": "CHS McPherson", "company": "CHS Inc.", "state": "KS", "county": "McPherson", "region": "Midwest (PADD2)",
     "lat": 38.00, "lon": -97.60, "capacity_kbd": 93},
    # Added to raise match coverage against Wood Mackenzie's monitored-unit universe (which is
    # broader than this originally curated "major refineries" list) — see wm_refinery_sync.py.
    {"name": "TotalEnergies Port Arthur", "company": "TotalEnergies", "state": "TX", "county": "Jefferson", "region": "Gulf Coast",
     "lat": 29.87, "lon": -93.93, "capacity_kbd": 238},
    {"name": "Citgo Corpus Christi", "company": "Citgo", "state": "TX", "county": "Nueces", "region": "Gulf Coast",
     "lat": 27.85, "lon": -97.43, "capacity_kbd": 157},
    {"name": "Lyondell Houston", "company": "LyondellBasell", "state": "TX", "county": "Harris", "region": "Gulf Coast",
     "lat": 29.73, "lon": -95.22, "capacity_kbd": 264},
    {"name": "Pemex Deer Park", "company": "Pemex", "state": "TX", "county": "Harris", "region": "Gulf Coast",
     "lat": 29.73, "lon": -95.13, "capacity_kbd": 340},
    {"name": "Flint Hills Corpus Christi", "company": "Flint Hills Resources", "state": "TX", "county": "Nueces", "region": "Gulf Coast",
     "lat": 27.85, "lon": -97.43, "capacity_kbd": 140},
    {"name": "Chevron Pasadena", "company": "Chevron", "state": "TX", "county": "Harris", "region": "Gulf Coast",
     "lat": 29.68, "lon": -95.13, "capacity_kbd": 110},
    {"name": "Marathon El Paso", "company": "Marathon", "state": "TX", "county": "El Paso", "region": "Gulf Coast",
     "lat": 31.76, "lon": -106.44, "capacity_kbd": 131},
    {"name": "GCC Bunkers Galveston", "company": "GCC Bunkers", "state": "TX", "county": "Galveston", "region": "Gulf Coast",
     "lat": 29.30, "lon": -94.80, "capacity_kbd": 50},
    {"name": "Marathon Mandan", "company": "Marathon", "state": "ND", "county": "Morton", "region": "Midwest (PADD2)",
     "lat": 46.83, "lon": -100.90, "capacity_kbd": 74},
    {"name": "Marathon Detroit", "company": "Marathon", "state": "MI", "county": "Wayne", "region": "Midwest (PADD2)",
     "lat": 42.31, "lon": -83.15, "capacity_kbd": 132},
    {"name": "Delek El Dorado", "company": "Delek US", "state": "AR", "county": "Union", "region": "Midwest (PADD2)",
     "lat": 33.21, "lon": -92.67, "capacity_kbd": 80},
]

EU_NWE_MED = [
    {"name": "Shell Pernis (Rotterdam)", "company": "Shell", "country": "Netherlands", "region": "NW Europe (ARA)",
     "lat": 51.88, "lon": 4.39, "capacity_kbd": 404},
    {"name": "BP Rotterdam (Europoort)", "company": "BP", "country": "Netherlands", "region": "NW Europe (ARA)",
     "lat": 51.93, "lon": 4.13, "capacity_kbd": 377},
    {"name": "ExxonMobil Rotterdam", "company": "ExxonMobil", "country": "Netherlands", "region": "NW Europe (ARA)",
     "lat": 51.90, "lon": 4.47, "capacity_kbd": 190},
    {"name": "TotalEnergies Antwerp", "company": "TotalEnergies", "country": "Belgium", "region": "NW Europe (ARA)",
     "lat": 51.28, "lon": 4.30, "capacity_kbd": 360},
    {"name": "ExxonMobil Antwerp", "company": "ExxonMobil", "country": "Belgium", "region": "NW Europe (ARA)",
     "lat": 51.32, "lon": 4.34, "capacity_kbd": 330},
    {"name": "Shell Rheinland (Wesseling/Godorf)", "company": "Shell", "country": "Germany", "region": "NW Europe",
     "lat": 50.85, "lon": 6.98, "capacity_kbd": 327},
    {"name": "TotalEnergies Leuna", "company": "TotalEnergies", "country": "Germany", "region": "NW Europe",
     "lat": 51.32, "lon": 12.05, "capacity_kbd": 236},
    {"name": "PCK Schwedt", "company": "PCK (Rosneft-linked)", "country": "Germany", "region": "NW Europe",
     "lat": 53.06, "lon": 14.28, "capacity_kbd": 233},
    {"name": "Heide Raffinerie", "company": "Klesch Group", "country": "Germany", "region": "NW Europe",
     "lat": 54.19, "lon": 9.10, "capacity_kbd": 90},
    {"name": "ExxonMobil Fawley", "company": "ExxonMobil", "country": "UK", "region": "NW Europe",
     "lat": 50.82, "lon": -1.33, "capacity_kbd": 270},
    {"name": "Valero Pembroke", "company": "Valero", "country": "UK", "region": "NW Europe",
     "lat": 51.68, "lon": -5.00, "capacity_kbd": 270},
    {"name": "Essar Stanlow", "company": "Essar", "country": "UK", "region": "NW Europe",
     "lat": 53.28, "lon": -2.85, "capacity_kbd": 207},
    {"name": "Galp Sines", "company": "Galp", "country": "Portugal", "region": "Mediterranean",
     "lat": 37.95, "lon": -8.85, "capacity_kbd": 220},
    {"name": "Repsol Cartagena", "company": "Repsol", "country": "Spain", "region": "Mediterranean",
     "lat": 37.60, "lon": -0.95, "capacity_kbd": 220},
    {"name": "Repsol Tarragona", "company": "Repsol", "country": "Spain", "region": "Mediterranean",
     "lat": 41.12, "lon": 1.20, "capacity_kbd": 186},
    {"name": "ISAB Priolo (Sicily)", "company": "Sonatrach", "country": "Italy", "region": "Mediterranean",
     "lat": 37.15, "lon": 15.18, "capacity_kbd": 320},
    {"name": "Saras Sarroch (Sardinia)", "company": "Saras", "country": "Italy", "region": "Mediterranean",
     "lat": 39.08, "lon": 9.02, "capacity_kbd": 300},
    {"name": "Eni Milazzo (Sicily)", "company": "Eni / KPC", "country": "Italy", "region": "Mediterranean",
     "lat": 38.22, "lon": 15.28, "capacity_kbd": 200},
    # Added to raise match coverage against Wood Mackenzie's monitored-unit universe.
    {"name": "TotalEnergies Donges", "company": "TotalEnergies", "country": "France", "region": "NW Europe",
     "lat": 47.31, "lon": -2.07, "capacity_kbd": 220},
    {"name": "TotalEnergies Normandy", "company": "TotalEnergies", "country": "France", "region": "NW Europe",
     "lat": 49.47, "lon": 0.23, "capacity_kbd": 247},
    {"name": "BP Castellon", "company": "BP", "country": "Spain", "region": "Mediterranean",
     "lat": 39.96, "lon": -0.05, "capacity_kbd": 110},
    {"name": "Moeve Huelva", "company": "Moeve (Cepsa)", "country": "Spain", "region": "Mediterranean",
     "lat": 37.25, "lon": -6.93, "capacity_kbd": 220},
    {"name": "Moeve San Roque", "company": "Moeve (Cepsa)", "country": "Spain", "region": "Mediterranean",
     "lat": 36.19, "lon": -5.38, "capacity_kbd": 240},
    {"name": "INEOS Lavera", "company": "INEOS", "country": "France", "region": "Mediterranean",
     "lat": 43.39, "lon": 5.03, "capacity_kbd": 240},
    {"name": "Repsol Bilbao", "company": "Repsol", "country": "Spain", "region": "Mediterranean",
     "lat": 43.33, "lon": -3.02, "capacity_kbd": 220},
    {"name": "TotalEnergies Feyzin", "company": "TotalEnergies", "country": "France", "region": "Mediterranean",
     "lat": 45.67, "lon": 4.87, "capacity_kbd": 110},
]


def all_refineries():
    out = []
    for r in US_GULF_MIDWEST:
        out.append({**r, "market": "US"})
    for r in EU_NWE_MED:
        out.append({**r, "market": "EU"})
    return out
